### ISSUE TITLE
EXE marked as containing trojan?

### ISSUE THREAD

**Issue by kneeil** [mhssamadani/ErgoStratumProxy#23]
I tried downloading the exe for ErgoStratumProxy 1.2.1, but my antivirus flags it as containing a virus (Trojan-PSW.Win32.Disco.ctp). Is it possible the exe (presumably unintentionally) ended up with the mentioned virus?

**Comment by kneeil** [comment]
In case it's helpful, here is a screenshot of my antivirus (Kaspersky) flagging the executable:

![image](https://user-images.githubusercontent.com/74897402/141671210-476d7376-5f22-4062-bd59-82a21028bb1c.png)

It also lists the MD5 as 9FC4238AC983EF1E2036FBD559B16DD5

Can provide additional info if helpful

**Comment by mhssamadani** [comment]
No, it's okay. Antiviruses almost always warn about miner-related applications due to lots of cryptographic operations. You can build yourself and compare the executable with the release.
